# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-13 15:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torchbox', '0022_signupformpage_signupformpagebullet_signupformpagelogo_signupformpagequote_signupformpageresponse'),
        ('torchbox', '0025_marketinglandingpagepageclients'),
    ]

    operations = [
    ]
