# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-10-10 09:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torchbox', '0090_auto_20170130_1032'),
        ('torchbox', '0095_set_blogpages_show_in_menus_true'),
        ('torchbox', '0093_auto_20170131_1151'),
    ]

    operations = [
    ]
