# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-04-16 13:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torchbox', '0096_merge'),
        ('torchbox', '0096_revert_pr97'),
    ]

    operations = [
    ]
