# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-06-08 08:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torchbox', '0097_merge'),
        ('torchbox', '0097_auto_20180607_1715'),
    ]

    operations = [
    ]
