# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-21 15:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torchbox', '0098_merge'),
        ('torchbox', '0099_auto_20180320_1631'),
    ]

    operations = [
    ]
